title: Stack Problems
description: My Personal Stack Problems
author: Zulkar Bedelbaev
github: https://github.com/zismailov
about: Software engineer. Currently doing more in backend, focused in Ruby and Ruby on Rails.
disqus_shortname: bedelbaev
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/pekrfh"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/zismailov"

share:
  twitter_username: pekrfh
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
      #url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://bedelbaev.com/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
